name: Docker Action

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: ckeckout
      uses: actions/checkout@v1


      
    - name: build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        image: raniaboughanmim/virtualization
        registry: docker.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}