name: Docker Action

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: ckeckout
      uses: actions/checkout@v3
   
    - name: build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: raniaboughanmim/virtualization:latest
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACESS }}


