name: Docker Action

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: ckeckout
      uses: actions/checkout@v1

    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        token: ${{ secrets.DOCKER_ACESS }}       
      
    - name: build and Push Docker image
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        file: ./Dockerfile
        tags: raniaboughanmim/virtualization:1.2

